export default [
  {
    login: 'adu013',
    id: 18141815,
    node_id: 'MDQ6VXNlcjE4MTQxODE1',
    avatar_url: 'https://avatars0.githubusercontent.com/u/18141815?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/adu013',
    html_url: 'https://github.com/adu013',
    followers_url: 'https://api.github.com/users/adu013/followers',
    following_url: 'https://api.github.com/users/adu013/following{/other_user}',
    gists_url: 'https://api.github.com/users/adu013/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/adu013/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/adu013/subscriptions',
    organizations_url: 'https://api.github.com/users/adu013/orgs',
    repos_url: 'https://api.github.com/users/adu013/repos',
    events_url: 'https://api.github.com/users/adu013/events{/privacy}',
    received_events_url: 'https://api.github.com/users/adu013/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'raddiakshay',
    id: 27286907,
    node_id: 'MDQ6VXNlcjI3Mjg2OTA3',
    avatar_url: 'https://avatars1.githubusercontent.com/u/27286907?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/raddiakshay',
    html_url: 'https://github.com/raddiakshay',
    followers_url: 'https://api.github.com/users/raddiakshay/followers',
    following_url:
      'https://api.github.com/users/raddiakshay/following{/other_user}',
    gists_url: 'https://api.github.com/users/raddiakshay/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/raddiakshay/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/raddiakshay/subscriptions',
    organizations_url: 'https://api.github.com/users/raddiakshay/orgs',
    repos_url: 'https://api.github.com/users/raddiakshay/repos',
    events_url: 'https://api.github.com/users/raddiakshay/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/raddiakshay/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'manishandroid',
    id: 4254384,
    node_id: 'MDQ6VXNlcjQyNTQzODQ=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/4254384?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/manishandroid',
    html_url: 'https://github.com/manishandroid',
    followers_url: 'https://api.github.com/users/manishandroid/followers',
    following_url:
      'https://api.github.com/users/manishandroid/following{/other_user}',
    gists_url: 'https://api.github.com/users/manishandroid/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/manishandroid/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/manishandroid/subscriptions',
    organizations_url: 'https://api.github.com/users/manishandroid/orgs',
    repos_url: 'https://api.github.com/users/manishandroid/repos',
    events_url: 'https://api.github.com/users/manishandroid/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/manishandroid/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'PikluDey21',
    id: 54834322,
    node_id: 'MDQ6VXNlcjU0ODM0MzIy',
    avatar_url: 'https://avatars3.githubusercontent.com/u/54834322?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/PikluDey21',
    html_url: 'https://github.com/PikluDey21',
    followers_url: 'https://api.github.com/users/PikluDey21/followers',
    following_url:
      'https://api.github.com/users/PikluDey21/following{/other_user}',
    gists_url: 'https://api.github.com/users/PikluDey21/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/PikluDey21/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/PikluDey21/subscriptions',
    organizations_url: 'https://api.github.com/users/PikluDey21/orgs',
    repos_url: 'https://api.github.com/users/PikluDey21/repos',
    events_url: 'https://api.github.com/users/PikluDey21/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/PikluDey21/received_events',
    type: 'User',
    site_admin: false,
  },
]
